"""initial

Revision ID: 33a71b8b0c78
Revises: 
Create Date: 2024-12-12 10:43:43.900501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a71b8b0c78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_configs',
    sa.Column('url', sa.String(256), nullable=False),
    sa.Column('name', sa.String(128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_configs_id'), 'camera_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camera_configs_id'), table_name='camera_configs')
    op.drop_table('camera_configs')
    # ### end Alembic commands ###